name: todo_list
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dynamic_color: ^1.6.6
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  staggered_grid_view_flutter: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
